# Generated by Django 6.1 on 2026-08-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DayLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_phone', models.CharField(max_length=30)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(max_length=100)),
                ('project_address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(blank=True, help_text='Set if the client booked from a specific catalog item page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['slot_start'],
                'indexes': [models.Index(fields=['slot_start', 'slot_end'], name='bookings_bo_slot_st_185f4e_idx')],
            },
        ),
    ]
