# Generated by Django 6.1 on 2026-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('whatsapp', 'WhatsApp')], default='mobile_money', max_length=20),
        ),
    ]
