# Generated by Django 6.1 on 2026-08-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_fr', models.CharField(max_length=150)),
                ('role_en', models.CharField(max_length=150)),
                ('bio_fr', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('is_before_after', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
